"""In-tree AI attribution detector and telemetry synthesizer.

Extracts observable, verifiable AI tooling signals from git commit trailers,
bot authors, and PR metadata to solve the AI telemetry attribution gap (SE 3.0).
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

import structlog

from gain.attribution.models import (
    AttributionReport,
    AttributionSignal,
    AttributionSignalType,
)
from gain.mcp.schemas.ai import ClaimClassification
from gain.model.ai import AiDeveloperTelemetry, AiToolType
from gain.model.commit import CanonicalCommit
from gain.model.pr import PullRequest

log = structlog.get_logger(__name__)


class AIAttributionDetector:
    """Detects in-tree AI developer assistance from commit trailers and metadata."""

    # Well-known AI coding assistant and reviewer bots
    KNOWN_AI_BOTS: set[str] = {
        "copilot[bot]",
        "github-copilot[bot]",
        "copilot-pull-request-reviewer[bot]",
        "cursor-agent[bot]",
        "cursor[bot]",
        "sweep[bot]",
        "coderabbitai[bot]",
        "sourcery-ai[bot]",
        "chatgpt-codereview[bot]",
        "deepcode[bot]",
        "tabnine[bot]",
        "amazon-q[bot]",
    }

    # Regex patterns for commit message trailers and indicators
    TRAILER_PATTERNS: list[tuple[re.Pattern[str], AiToolType, float]] = [
        (
            re.compile(r"co-authored-by:\s*.*copilot.*<.*>", re.IGNORECASE),
            AiToolType.COPILOT,
            0.99,
        ),
        (
            re.compile(r"co-authored-by:\s*.*claude.*<.*>", re.IGNORECASE),
            AiToolType.CLAUDE_DEV,
            0.99,
        ),
        (
            re.compile(r"co-authored-by:\s*.*anthropic.*<.*>", re.IGNORECASE),
            AiToolType.CLAUDE_DEV,
            0.99,
        ),
        (
            re.compile(r"co-authored-by:\s*.*cursor.*<.*>", re.IGNORECASE),
            AiToolType.CURSOR,
            0.99,
        ),
        (
            re.compile(r"generated-by:\s*.*cursor.*", re.IGNORECASE),
            AiToolType.CURSOR,
            0.95,
        ),
        (
            re.compile(r"co-authored-by:\s*.*codeium.*<.*>", re.IGNORECASE),
            AiToolType.OTHER,
            0.95,
        ),
        (
            re.compile(r"co-authored-by:\s*.*chatgpt.*<.*>", re.IGNORECASE),
            AiToolType.OTHER,
            0.95,
        ),
        (
            re.compile(r"assisted-by:\s*.*(copilot|cursor|claude|ai).*", re.IGNORECASE),
            AiToolType.OTHER,
            0.90,
        ),
        (
            re.compile(r"ai-generated:\s*true", re.IGNORECASE),
            AiToolType.OTHER,
            0.90,
        ),
    ]

    MESSAGE_PREFIX_PATTERNS: list[tuple[re.Pattern[str], AiToolType, float]] = [
        (re.compile(r"^\[cursor\]", re.IGNORECASE), AiToolType.CURSOR, 0.85),
        (re.compile(r"^\[copilot\]", re.IGNORECASE), AiToolType.COPILOT, 0.85),
        (re.compile(r"^sweep:", re.IGNORECASE), AiToolType.OTHER, 0.90),
        (re.compile(r"generated with cursor composer", re.IGNORECASE), AiToolType.CURSOR, 0.95),
        (re.compile(r"generated by copilot", re.IGNORECASE), AiToolType.COPILOT, 0.95),
    ]

    def detect_commit_signals(self, commit: CanonicalCommit) -> list[AttributionSignal]:
        """Extract AI attribution signals from a canonical commit."""
        signals: list[AttributionSignal] = []
        msg = commit.message

        # 1. Trailer checks
        for pattern, tool_type, confidence in self.TRAILER_PATTERNS:
            match = pattern.search(msg)
            if match:
                signals.append(
                    AttributionSignal(
                        signal_type=AttributionSignalType.TRAILER,
                        tool_type=tool_type,
                        confidence=confidence,
                        source_identifier=f"commit:{commit.sha[:8]}",
                        evidence_text=match.group(0).strip(),
                    )
                )

        # 2. Subject / message body checks
        for pattern, tool_type, confidence in self.MESSAGE_PREFIX_PATTERNS:
            match = pattern.search(msg)
            if match:
                signals.append(
                    AttributionSignal(
                        signal_type=AttributionSignalType.COMMIT_MESSAGE,
                        tool_type=tool_type,
                        confidence=confidence,
                        source_identifier=f"commit:{commit.sha[:8]}",
                        evidence_text=match.group(0).strip(),
                    )
                )

        # 3. Author login check if known bot
        if commit.author_login and commit.author_login.lower() in self.KNOWN_AI_BOTS:
            signals.append(
                AttributionSignal(
                    signal_type=AttributionSignalType.BOT_AUTHOR,
                    tool_type=self._bot_to_tool_type(commit.author_login),
                    confidence=1.0,
                    source_identifier=f"commit_author:{commit.author_login}",
                    evidence_text=f"Author login '{commit.author_login}' is a recognized AI agent",
                )
            )

        return signals

    def detect_pr_signals(
        self, pr: PullRequest, commits: list[CanonicalCommit] | None = None
    ) -> list[AttributionSignal]:
        """Extract AI attribution signals for a pull request."""
        signals: list[AttributionSignal] = []

        # 1. Bot author check
        if pr.author_login and pr.author_login.lower() in self.KNOWN_AI_BOTS:
            signals.append(
                AttributionSignal(
                    signal_type=AttributionSignalType.BOT_AUTHOR,
                    tool_type=self._bot_to_tool_type(pr.author_login),
                    confidence=1.0,
                    source_identifier=f"pr_author:{pr.author_login}",
                    evidence_text=f"PR author '{pr.author_login}' is a recognized AI agent",
                )
            )

        # 2. Associated commits check
        if commits:
            for commit in commits:
                commit_signals = self.detect_commit_signals(commit)
                signals.extend(commit_signals)

        return signals

    def analyze_repository(
        self,
        repository: str,
        prs: list[PullRequest],
        commits: list[CanonicalCommit] | None = None,
    ) -> AttributionReport:
        """Audit repository telemetry and generate an in-tree attribution report."""
        commits = commits or []
        ai_pr_count = 0
        ai_commit_count = 0
        detected_tools: set[AiToolType] = set()
        ai_authors: set[str] = set()
        all_signals: list[AttributionSignal] = []

        # Map commits by author login or email
        for c in commits:
            signals = self.detect_commit_signals(c)
            if signals:
                ai_commit_count += 1
                all_signals.extend(signals)
                for s in signals:
                    detected_tools.add(s.tool_type)
                author = c.author_login or c.author_email or c.author_name
                if author:
                    ai_authors.add(author)

        for pr in prs:
            pr_signals = self.detect_pr_signals(pr)
            # Also check if PR author is an identified AI author
            if pr.author_login and pr.author_login in ai_authors:
                ai_pr_count += 1
            elif pr_signals:
                ai_pr_count += 1
                all_signals.extend(pr_signals)
                for s in pr_signals:
                    detected_tools.add(s.tool_type)
                if pr.author_login:
                    ai_authors.add(pr.author_login)

        total_prs = len(prs)
        penetration = round(ai_pr_count / max(1, total_prs), 4)

        return AttributionReport(
            repository=repository,
            total_prs=total_prs,
            ai_assisted_prs=ai_pr_count,
            total_commits=len(commits),
            ai_assisted_commits=ai_commit_count,
            ai_penetration_rate=penetration,
            detected_tools=sorted(list(detected_tools), key=lambda x: str(x.value)),
            ai_active_developers=sorted(list(ai_authors)),
            signals=all_signals,
            epistemic_classification=(
                ClaimClassification.OBSERVED if all_signals else ClaimClassification.UNKNOWN
            ),
        )

    def synthesize_developer_telemetry(
        self,
        repository: str,
        prs: list[PullRequest],
        commits: list[CanonicalCommit] | None = None,
        window_start: datetime | None = None,
        window_end: datetime | None = None,
    ) -> list[AiDeveloperTelemetry]:
        """Synthesize developer adoption records from observable commit and PR activity."""
        report = self.analyze_repository(repository, prs, commits)
        ai_authors = set(report.ai_active_developers)

        start = window_start or (
            min((p.created_at for p in prs), default=datetime(2026, 1, 1, tzinfo=UTC))
        )
        end = window_end or (
            max((p.created_at for p in prs), default=datetime(2026, 2, 1, tzinfo=UTC))
        )

        # Group stats by author
        author_stats: dict[str, dict[str, int]] = {}
        for p in prs:
            author = p.author_login or "unknown"
            stats = author_stats.setdefault(author, {"prs": 0, "additions": 0, "deletions": 0})
            stats["prs"] += 1
            stats["additions"] += p.additions or 0
            stats["deletions"] += p.deletions or 0

        telemetry: list[AiDeveloperTelemetry] = []
        for author, stats in author_stats.items():
            is_active = author in ai_authors
            tool = (
                report.detected_tools[0]
                if (is_active and report.detected_tools)
                else (AiToolType.COPILOT)
            )
            # Estimate suggestions/acceptances from observed churn
            adds = stats["additions"]
            telemetry.append(
                AiDeveloperTelemetry(
                    developer_id=author,
                    repository=repository,
                    tool_type=tool,
                    window_start=start,
                    window_end=end,
                    active_days=min(30, max(1, stats["prs"] * 2)),
                    suggestions_count=int(adds * 1.5) if is_active else 0,
                    acceptances_count=adds if is_active else 0,
                    lines_suggested=int(adds * 1.5) if is_active else 0,
                    lines_accepted=adds if is_active else 0,
                    is_ai_active=is_active,
                )
            )

        return telemetry

    @staticmethod
    def _bot_to_tool_type(login: str) -> AiToolType:
        low = login.lower()
        if "copilot" in low:
            return AiToolType.COPILOT
        if "cursor" in low:
            return AiToolType.CURSOR
        if "claude" in low:
            return AiToolType.CLAUDE_DEV
        return AiToolType.OTHER
